### ISSUE TITLE
Segfault if SealedBox pubkey is null

### ISSUE THREAD

**Issue by ysangkok** [abstractj/kalium#47]
See https://github.com/ysangkok/NaclTest/blob/master/src/main/java/com/mycompany/nacltest/NaclTest.java

If I change the public key parameter to null (public key shouldn't be needed for decryption, right?), the JVM crashes.

Even if a public key is needed, it should not segfault, it could throw an exception.

Why are annotations such as @Nullable not used?

Thanks for you efforts however, the library is useful.

**Comment by bendoerr** [comment]
I recall that the recipients public key is required for decryption of a sealed box (as the code suggests) as it's used for building the box's nonce. Secret box (as the title suggests) uses a symmetric key and is required.

From the libsodium documentation: The format of a sealed box is
`ephemeral_pk || box(m, recipient_pk, ephemeral_sk, nonce=blake2b(ephemeral_pk || recipient_pk))`

This means that to decrypt construction looks like `box_open(c, recipient_sk, ephemeral_pk, nonce=blake2b(ephemeral_pk || recipient_pk))`

On the note of nullable, I can't think of any of the Kalium API's that would allow for null value. I do agree that a runtime exception would be much better than a full segfault.

I just added the SealedBox API, I crammed the encrypt and decrypt interfaces together into one class with two constructors for the different purposes. Do you think there should be separate classes since the encrypt and decrypt operations are not symmetric in terms of how the instance is constructed like both Box and SecretBox are? Maybe hide the constructors and provide static instantiators making their purpose clear?

**Comment by ysangkok** [comment]
When you say symmetric, what exactly do you mean? Do you mean non-bijective?

Preventing misuse of the API is good, of course it is an advantage if the type system prevents errors.

However, this is not too important. Why are objects used at all anyway? I am not convinced that most people need to decrypt or encrypt multiple things with the same key. Static methods would also suffice. The abstraction makes little sense because there is no way I would, using my intuition, figure out that the keys are part of the "box".

I think it is most important to prevent crashing the JVM though, that should not be needed. That is the whole purpose of a wrapper library: to conveniently wrap the native code. Since the native code implements the actual functionality, this amounts to nothing but catching errors.

**Comment by abstractj** [comment]
@ysangkok @bendoerr I believe this change https://github.com/abstractj/kalium/pull/60 fixes the issue, right? Just let me know and we get it merged.

**Comment by ysangkok** [comment]
@abstractj Yes, works.

**Comment by abstractj** [comment]
Landed here: https://github.com/abstractj/kalium/commit/481dc82c0f662d7841394925de12d45eca09931a
