### ISSUE TITLE
New release to support library name differences in NaCl?

### ISSUE THREAD

**Issue by agarbutt** [abstractj/kalium#70]
I recently ran into the issue described in #65.   I see that it is marked as revolved and merged.  Do you have an ETA for a release of kalium with this change?  Or should I post a PR with doc changes suggesting how to work around this?

**Comment by mgrand** [comment]
I am just going to clone the repo and build the latest snapshot. I need the library to work in a windows environment.

**Comment by AwakenedRage98** [comment]
I was never able to get it to work in a Windows Environment for Windows 7 and Windows 8.1
I tried for days to figure out where it was looking for the sodium libraries and I was not able to pinpoint a location, even with the information from previous issues. 

Since I was making a server side application that needed to encrypt data, I just ended up installing Kalium dependencies in a Linux Virtual Machine and I am developing from it and I am having no problems. It would be nice though if someone could figure it out.

**Comment by abstractj** [comment]
@agarbutt @mgrand @AwakenedRage98  I have no idea about Windows. if someone has the solution for Windows, well tested with testing passing in whatever CI. I will be more than happy to include.

**Comment by agarbutt** [comment]
I'll try and take a look at this today.

**Comment by agarbutt** [comment]
Added a pull request #81 to update the documentation for Windows installations.

Note, that in my testing, the current `master` supports the correct name of the library on the Windows platform for at least the following versions of libsodium: `1.0.10`, `1.0.11`, and `1.0.12`

**Comment by abstractj** [comment]
@agarbutt @mgrand Kalium 0.7.0 was released. Just give some hours for Maven nexus to synchronize

Closing it for now.
